from typing import Dict, Optional


README_TEMPLATE = """# {name}

> Generated by BuilderAI — Multi-Agent AI App Builder

## 🚀 Quick Start

```bash
# Install dependencies
npm install

# Set up environment variables
cp .env.example .env.local
# Fill in your Supabase and other credentials

# Run development server
npm run dev
```

Open [http://localhost:5173](http://localhost:5173) in your browser.

## 📁 Project Structure

```
{file_tree}
```

## 🔧 Environment Variables

See `.env.example` for required environment variables.

## 🚀 Deploy

1. Push to GitHub
2. Import in Vercel / Netlify
3. Set environment variables
4. Deploy!

## 🤖 Built with BuilderAI

This app was generated by [BuilderAI](https://builderai.app) using a multi-agent AI pipeline:
- **Architect Agent** — Designed the app structure
- **Frontend Agent** — Generated React/Vite components
- **Validator** — Reviewed and fixed issues
"""

ENV_EXAMPLE_TEMPLATE = """# Supabase (only needed if storage is supabase)
VITE_SUPABASE_URL=your_supabase_url
VITE_SUPABASE_ANON_KEY=your_supabase_anon_key

# Add any other environment variables your app needs
"""


def build_file_tree_string(files: Dict[str, str], max_depth: int = 3) -> str:
    """Build a tree string representation of the file structure."""
    tree_lines = []

    # Sort and organize
    sorted_paths = sorted(files.keys())

    # Build a simple tree
    seen_dirs = set()
    for path in sorted_paths:
        parts = path.split('/')
        for i, part in enumerate(parts):
            indent = '  ' * i
            if i < len(parts) - 1:
                dir_path = '/'.join(parts[:i+1])
                if dir_path not in seen_dirs:
                    seen_dirs.add(dir_path)
                    tree_lines.append(f"{indent}├── {part}/")
            else:
                tree_lines.append(f"{indent}├── {part}")

    return '\n'.join(tree_lines[:50])  # Cap at 50 lines


def add_project_metadata(
    files: Dict[str, str],
    project_name: str,
    dependencies: Optional[list] = None,
) -> Dict[str, str]:
    """Add README, .env.example, and ensure package.json exists."""
    enriched = dict(files)

    # Add README
    file_tree = build_file_tree_string(files)
    enriched['README.md'] = README_TEMPLATE.format(
        name=project_name,
        file_tree=file_tree,
    )

    # Add .env.example
    enriched['.env.example'] = ENV_EXAMPLE_TEMPLATE

    # Ensure package.json exists
    if 'package.json' not in enriched:
        enriched['package.json'] = """{
  "name": "builderai-project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.0",
    "react-dom": "^18.3.0"
  },
  "devDependencies": {
    "typescript": "^5.0.0",
    "@types/node": "^20.0.0",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@vitejs/plugin-react": "^4.3.0",
    "vite": "^5.4.0",
    "tailwindcss": "^3.4.0",
    "autoprefixer": "^10.4.0",
    "postcss": "^8.0.0"
  }
}
"""

    # Ensure tsconfig.json
    if 'tsconfig.json' not in enriched:
        enriched['tsconfig.json'] = """{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["dom", "dom.iterable", "ES2020"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "paths": {"@/*": ["./src/*"]}
  },
  "include": ["src/**/*.ts", "src/**/*.tsx", "vite-env.d.ts"],
  "exclude": ["node_modules"]
}
"""

    # Ensure vite.config.ts exists
    has_vite_config = any(
        k in enriched for k in ('vite.config.ts', 'vite.config.js', 'vite.config.mjs')
    )
    if not has_vite_config:
        enriched['vite.config.ts'] = """import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
})
"""

    # Ensure index.html exists (Vite entry point — mandatory, without this npm run dev fails)
    if 'index.html' not in enriched:
        enriched['index.html'] = (
            '<!DOCTYPE html>\n'
            '<html lang="en">\n'
            '  <head>\n'
            '    <meta charset="UTF-8" />\n'
            '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
            '    <title>App</title>\n'
            '  </head>\n'
            '  <body>\n'
            '    <div id="root"></div>\n'
            '    <script type="module" src="/src/main.tsx"></script>\n'
            '  </body>\n'
            '</html>\n'
        )

    # Ensure src/index.css exists with Tailwind v3 directives
    css_path = next(
        (k for k in enriched if k in ('src/index.css', 'app/globals.css', 'src/app/globals.css')), None
    )
    if css_path is None:
        # No CSS at all — inject a minimal one
        enriched['src/index.css'] = """@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
    --card: 0 0% 100%;
    --card-foreground: 222.2 84% 4.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 222.2 84% 4.9%;
    --primary: 222.2 47.4% 11.2%;
    --primary-foreground: 210 40% 98%;
    --secondary: 210 40% 96.1%;
    --secondary-foreground: 222.2 47.4% 11.2%;
    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;
    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 210 40% 98%;
    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;
    --ring: 222.2 84% 4.9%;
    --radius: 0.5rem;
  }
  .dark {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;
    --card: 222.2 84% 4.9%;
    --card-foreground: 210 40% 98%;
    --popover: 222.2 84% 4.9%;
    --popover-foreground: 210 40% 98%;
    --primary: 210 40% 98%;
    --primary-foreground: 222.2 47.4% 11.2%;
    --secondary: 217.2 32.6% 17.5%;
    --secondary-foreground: 210 40% 98%;
    --muted: 217.2 32.6% 17.5%;
    --muted-foreground: 215 20.2% 65.1%;
    --accent: 217.2 32.6% 17.5%;
    --accent-foreground: 210 40% 98%;
    --destructive: 0 62.8% 30.6%;
    --destructive-foreground: 210 40% 98%;
    --border: 217.2 32.6% 17.5%;
    --input: 217.2 32.6% 17.5%;
    --ring: 212.7 26.8% 83.9%;
  }
}

@layer base {
  * { @apply border-border; }
  body { @apply bg-background text-foreground; }
}
"""
    else:
        # Fix v4-style @import directive to v3-compatible directives
        css = enriched[css_path]
        if '@import "tailwindcss"' in css or "@import 'tailwindcss'" in css:
            css = css.replace('@import "tailwindcss"', '@tailwind base;\n@tailwind components;\n@tailwind utilities;')
            css = css.replace("@import 'tailwindcss'", '@tailwind base;\n@tailwind components;\n@tailwind utilities;')
            enriched[css_path] = css
        elif '@import "tailwindcss/' in css or "@import 'tailwindcss/" in css:
            import re as _re
            css = _re.sub(r'''@import ['"]tailwindcss/[^'"]+['"];?\s*''', '', css)
            if not any(d in css for d in ('@tailwind base', '@tailwind components', '@tailwind utilities')):
                css = '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n' + css
            enriched[css_path] = css
        # Rename legacy path to src/index.css
        if css_path != 'src/index.css':
            enriched['src/index.css'] = enriched.pop(css_path)

    return enriched
