const GITHUB_API = 'https://api.github.com'

/** Convert a project name to a valid GitHub repo name */
export function slugifyRepoName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 100) || 'builderai-project'
}

export class GitHubApiError extends Error {
  status: number
  constructor(message: string, status: number) {
    super(message)
    this.name = 'GitHubApiError'
    this.status = status
  }
}

/** Authenticated fetch wrapper for GitHub API */
export async function githubApi<T = unknown>(
  token: string,
  path: string,
  options: RequestInit = {}
): Promise<T> {
  const res = await fetch(`${GITHUB_API}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

  if (!res.ok) {
    const body = await res.json().catch(() => ({ message: res.statusText }))
    throw new GitHubApiError(
      body.message || `GitHub API error: ${res.status}`,
      res.status
    )
  }

  return res.json() as Promise<T>
}

interface PushResult {
  repoUrl: string
  repoName: string
}

/**
 * Push all project files to a new GitHub repository.
 * Uses the Git Data API (blobs → tree → commit → ref update).
 */
export async function pushToGitHub(
  token: string,
  username: string,
  files: Record<string, string>,
  options: { repoName: string; isPrivate?: boolean; commitMessage?: string }
): Promise<PushResult> {
  const { repoName, isPrivate = false, commitMessage = 'Initial commit from BuilderAI' } = options

  // 1. Create the repository (auto_init creates an initial commit + main branch)
  const repo = await githubApi<{ full_name: string; html_url: string; default_branch: string }>(
    token,
    '/user/repos',
    {
      method: 'POST',
      body: JSON.stringify({
        name: repoName,
        private: isPrivate,
        auto_init: true,
        description: 'Generated by BuilderAI',
      }),
    }
  )

  const owner = username
  const branch = repo.default_branch || 'main'

  // 2. Get current commit SHA on default branch
  const ref = await githubApi<{ object: { sha: string } }>(
    token,
    `/repos/${owner}/${repoName}/git/ref/heads/${branch}`
  )
  const baseCommitSha = ref.object.sha

  // Get the commit to find its tree SHA
  const baseCommit = await githubApi<{ tree: { sha: string } }>(
    token,
    `/repos/${owner}/${repoName}/git/commits/${baseCommitSha}`
  )

  // 3. Create blobs for all files (in batches of 10 to avoid rate limits)
  const fileEntries = Object.entries(files)
  const treeItems: { path: string; mode: string; type: string; sha: string }[] = []

  const BATCH_SIZE = 10
  for (let i = 0; i < fileEntries.length; i += BATCH_SIZE) {
    const batch = fileEntries.slice(i, i + BATCH_SIZE)
    const results = await Promise.all(
      batch.map(async ([filePath, content]) => {
        const blob = await githubApi<{ sha: string }>(
          token,
          `/repos/${owner}/${repoName}/git/blobs`,
          {
            method: 'POST',
            body: JSON.stringify({
              content: Buffer.from(content).toString('base64'),
              encoding: 'base64',
            }),
          }
        )
        return { path: filePath, mode: '100644' as const, type: 'blob' as const, sha: blob.sha }
      })
    )
    treeItems.push(...results)
  }

  // 4. Create a tree from all blobs
  const tree = await githubApi<{ sha: string }>(
    token,
    `/repos/${owner}/${repoName}/git/trees`,
    {
      method: 'POST',
      body: JSON.stringify({
        base_tree: baseCommit.tree.sha,
        tree: treeItems,
      }),
    }
  )

  // 5. Create a commit
  const commit = await githubApi<{ sha: string }>(
    token,
    `/repos/${owner}/${repoName}/git/commits`,
    {
      method: 'POST',
      body: JSON.stringify({
        message: commitMessage,
        tree: tree.sha,
        parents: [baseCommitSha],
      }),
    }
  )

  // 6. Update the ref to point to the new commit
  await githubApi(
    token,
    `/repos/${owner}/${repoName}/git/refs/heads/${branch}`,
    {
      method: 'PATCH',
      body: JSON.stringify({ sha: commit.sha, force: true }),
    }
  )

  return { repoUrl: repo.html_url, repoName }
}
