import time
from graph.state import BuilderState
from prompts.backend_prompt import BACKEND_SYSTEM, BACKEND_USER
from utils.code_parser import parse_file_blocks
from utils.llm_provider import call_llm


def backend_agent(state: BuilderState) -> BuilderState:
    """
    Backend Agent: Generates API routes, database schema, and server-side logic.
    Runs in parallel with the frontend agent.
    """
    start_time = time.time()
    blueprint = state.get("blueprint", {})
    frontend_files = state.get("frontend_files", {})

    frontend_summary = "\n".join([
        f"- {path}: {content[:200]}..."
        for path, content in list((frontend_files or {}).items())[:5]
    ]) or "Frontend files not yet available."

    user_message = BACKEND_USER.format(
        blueprint=str(blueprint),
        frontend_summary=frontend_summary,
    )

    # Iteration mode: provide previous backend files as context
    prev_files = state.get("previous_files") or {}
    prev_backend = {
        k: v for k, v in prev_files.items()
        if k.startswith("app/api/") or k.endswith(".sql")
    }
    if prev_backend:
        snippets = []
        for path, content in list(prev_backend.items())[:10]:
            snippet = content[:500] + ("..." if len(content) > 500 else "")
            snippets.append(f"### {path}\n```\n{snippet}\n```")
        user_message += (
            "\n\n--- ITERATION CONTEXT ---\n"
            "IMPORTANT: The user is ITERATING on an existing app. Below are EXISTING backend files.\n"
            "Only regenerate files that need changes based on the updated blueprint.\n"
            "Files you don't output will be PRESERVED as-is from the previous build.\n\n"
            + "\n\n".join(snippets)
        )

    # QA remediation context
    qa_feedback = state.get("qa_feedback")
    if qa_feedback and qa_feedback.get("failed_agent") == "backend":
        issues = qa_feedback.get("issues", [])[:3]
        issue_lines = "\n".join([f"- [{i.get('severity','').upper()}] {i.get('description','')}" for i in issues])
        user_message += (
            "\n\n--- QA REMEDIATION REQUIRED ---\n"
            "The previous build failed QA review. Fix these critical backend issues:\n"
            f"{issue_lines}\n"
        )

    # If storage is localstorage or none, skip backend entirely — no error
    storage = blueprint.get("storage", "localstorage").lower()
    if storage in ("localstorage", "none"):
        duration_ms = int((time.time() - start_time) * 1000)
        return {
            **state,
            "backend_files": {},
            "events": [
                {
                    "type": "agent_complete",
                    "agent": "backend",
                    "message": "No backend needed (localStorage app)",
                    "duration_ms": duration_ms,
                },
                {
                    "type": "text",
                    "content": "Backend Agent skipped — app uses localStorage, no API routes needed.\n",
                },
            ],
        }

    try:
        llm_response = call_llm(
            system_prompt=BACKEND_SYSTEM,
            user_message=user_message,
            agent_name="backend",
            llm_mode=state.get("llm_mode"),
            llm_model=state.get("llm_model"),
        )

        raw_output = llm_response.content
        backend_files = parse_file_blocks(raw_output)

        if not backend_files:
            raise ValueError("No files generated by backend agent")

        if prev_backend:
            merged = {**prev_backend, **backend_files}
            backend_files = merged

        duration_ms = int((time.time() - start_time) * 1000)
        file_count = len(backend_files)

        events = [
            {
                "type": "agent_complete",
                "agent": "backend",
                "message": f"Generated {file_count} backend files",
                "duration_ms": duration_ms,
            },
            {
                "type": "text",
                "content": f"Backend Agent generated **{file_count} files**: {', '.join(list(backend_files.keys())[:5])}{'...' if file_count > 5 else ''}\n",
            },
            {
                "type": "files_update",
                "files": backend_files,
                "agent": "backend",
            },
        ]
        if llm_response.usage:
            input_t = llm_response.usage.get("input_tokens", 0)
            output_t = llm_response.usage.get("output_tokens", 0)
            events.append({
                "type": "usage",
                "agent": "backend",
                "input_tokens": input_t,
                "output_tokens": output_t,
                "cost_usd": round((input_t * 3.0 + output_t * 15.0) / 1_000_000, 6),
            })

        return {
            **state,
            "backend_files": backend_files,
            "events": events,
        }
    except Exception as e:
        return {
            **state,
            "errors": [f"Backend error: {str(e)}"],
            "events": [
                {
                    "type": "agent_error",
                    "agent": "backend",
                    "message": f"Failed to generate backend: {str(e)}",
                }
            ],
        }
