import logging
import time
from graph.state import BuilderState

logger = logging.getLogger(__name__)
from prompts.frontend_prompt import FRONTEND_SYSTEM, FRONTEND_USER, build_frontend_user
from utils.code_parser import parse_file_blocks, extract_plan_block, extract_verify_block
from utils.llm_provider import call_llm


def frontend_agent(state: BuilderState) -> BuilderState:
    """
    Frontend Agent: Generates React/Next.js components and pages based on the blueprint.
    Runs in parallel with the backend agent.
    """
    start_time = time.time()
    blueprint = state.get("blueprint", {})

    user_message = build_frontend_user(blueprint)

    # Iteration mode: provide previous frontend files as context
    prev_files = state.get("previous_files") or {}
    prev_frontend = {
        k: v for k, v in prev_files.items()
        if (k.startswith("app/") or k.startswith("components/") or k.startswith("lib/"))
        and not k.startswith("app/api/")
    }
    if prev_frontend:
        snippets = []
        for path, content in list(prev_frontend.items())[:10]:
            snippet = content[:500] + ("..." if len(content) > 500 else "")
            snippets.append(f"### {path}\n```\n{snippet}\n```")
        user_message += (
            "\n\n--- ITERATION CONTEXT ---\n"
            "IMPORTANT: The user is ITERATING on an existing app. Below are EXISTING frontend files.\n"
            "Only regenerate files that need changes based on the updated blueprint.\n"
            "Files you don't output will be PRESERVED as-is from the previous build.\n\n"
            + "\n\n".join(snippets)
        )

    # QA remediation context
    qa_feedback = state.get("qa_feedback")
    if qa_feedback and qa_feedback.get("failed_agent") == "frontend":
        issues = qa_feedback.get("issues", [])[:3]
        issue_lines = "\n".join([f"- [{i.get('severity','').upper()}] {i.get('description','')}" for i in issues])
        user_message += (
            "\n\n--- QA REMEDIATION REQUIRED ---\n"
            "The previous build failed QA review. Fix these critical frontend issues:\n"
            f"{issue_lines}\n"
        )

    try:
        llm_response = call_llm(
            system_prompt=FRONTEND_SYSTEM,
            user_message=user_message,
            agent_name="frontend",
            llm_mode=state.get("llm_mode"),
            llm_model=state.get("llm_model"),
        )

        raw_output = llm_response.content
        logger.info(
            "[frontend] LLM I/O sizes — input: %d chars, output: %d chars",
            len(user_message), len(raw_output)
        )
        frontend_files = parse_file_blocks(raw_output)

        if not frontend_files:
            raise ValueError("No files generated by frontend agent")

        if prev_frontend:
            merged = {**prev_frontend, **frontend_files}
            frontend_files = merged

        duration_ms = int((time.time() - start_time) * 1000)
        file_count = len(frontend_files)

        events = []

        # ── Capture extended thinking (API mode only) ─────────────────
        if llm_response.thinking:
            thinking_preview = llm_response.thinking[:2000]
            events.append({
                "type": "agent_thinking",
                "agent": "frontend",
                "content": thinking_preview,
            })
            logger.info(
                f"[frontend] Extended thinking ({len(llm_response.thinking)} chars):\n"
                f"{llm_response.thinking[:3000]}"
            )

        # ── Capture PLAN block (prompt-based reasoning) ───────────────
        plan_block = extract_plan_block(raw_output)
        if plan_block:
            events.append({
                "type": "agent_plan",
                "agent": "frontend",
                "content": plan_block[:2000],
            })
            logger.info(f"[frontend] PLAN:\n{plan_block[:3000]}")

        # ── Capture VERIFY block (self-check) ─────────────────────────
        verify_block = extract_verify_block(raw_output)
        if verify_block:
            events.append({
                "type": "agent_verify",
                "agent": "frontend",
                "content": verify_block[:2000],
            })
            logger.info(f"[frontend] VERIFY:\n{verify_block[:3000]}")

            # Log any issues found in VERIFY
            if "✗" in verify_block:
                issues = [line.strip() for line in verify_block.split('\n') if '✗' in line]
                if issues:
                    logger.warning(f"[frontend] VERIFY found {len(issues)} issues: {issues}")

        events.extend([
            {
                "type": "agent_complete",
                "agent": "frontend",
                "message": f"Generated {file_count} frontend files",
                "duration_ms": duration_ms,
            },
            {
                "type": "text",
                "content": f"Frontend Agent generated **{file_count} files**: {', '.join(list(frontend_files.keys())[:5])}{'...' if file_count > 5 else ''}\n",
            },
            {
                "type": "files_update",
                "files": frontend_files,
                "agent": "frontend",
            },
        ])
        if llm_response.usage:
            input_t = llm_response.usage.get("input_tokens", 0)
            output_t = llm_response.usage.get("output_tokens", 0)
            events.append({
                "type": "usage",
                "agent": "frontend",
                "input_tokens": input_t,
                "output_tokens": output_t,
                "cost_usd": round((input_t * 3.0 + output_t * 15.0) / 1_000_000, 6),
            })

        return {
            **state,
            "frontend_files": frontend_files,
            "_frontend_raw_output": raw_output,  # for plan cross-check in validate_and_finalize
            "events": events,
        }
    except Exception as e:
        return {
            **state,
            "errors": [f"Frontend error: {str(e)}"],
            "events": [
                {
                    "type": "agent_error",
                    "agent": "frontend",
                    "message": f"Failed to generate frontend: {str(e)}",
                }
            ],
        }
