import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'
import JSZip from 'jszip'

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params
  const supabase = await createClient()

  if (!supabase) {
    return NextResponse.json({ error: 'Download not available in dev mode (no Supabase)' }, { status: 404 })
  }

  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { data: project } = await supabase
    .from('projects')
    .select('*')
    .eq('id', id)
    .eq('user_id', user.id)
    .single()

  if (!project || !project.generated_files) {
    return NextResponse.json({ error: 'No files to download' }, { status: 404 })
  }

  const zip = new JSZip()
  const files = project.generated_files as Record<string, string>

  Object.entries(files).forEach(([path, content]) => {
    zip.file(path, content)
  })

  // Auto-generate README if one doesn't exist in the generated files
  if (!files['README.md']) {
    const readme = `# ${project.name}\n\n${project.description || project.prompt || ''}\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nOpen [http://localhost:3000](http://localhost:3000) in your browser.\n\n---\n\n*Generated by [BuilderAI](https://builderai.dev)*\n`
    zip.file('README.md', readme)
  }

  const zipArrayBuffer = await zip.generateAsync({ type: 'arraybuffer' })
  const filename = `${project.name.toLowerCase().replace(/\s+/g, '-')}.zip`

  return new Response(zipArrayBuffer, {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  })
}
